neo4j:
  uri: bolt://prod-neo4j:7687
  username: neo4j
  password: neo4j
  database: neo4j
  max_connection_pool_size: 50
sync:
  batch_size: 200
  parallel_workers: 8
  retry:
    attempts: 3
    backoff_seconds: 2
  initial_resync: true
  interval_seconds: 300
  job_cron: "0 7 * * *"
  source:
    base_url: ""
    snapshot_api: "/api/v1/snapshot"
    auth_header: "Authorization"
    static_token: ""
    auth_endpoint: ""
    username: ""
    password: ""
http:
  listen: ":8080"
